// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk8VrTqs1uMdwYyWDMkcxwbJvqLotJPVE',
    appId: '1:317198605296:web:a20953c7c51f09a4e35b35',
    messagingSenderId: '317198605296',
    projectId: 'classmate-e1d7f',
    authDomain: 'classmate-e1d7f.firebaseapp.com',
    storageBucket: 'classmate-e1d7f.firebasestorage.app',
    measurementId: 'G-8XT62EXXWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALFVwFkzogHTVy4k2V8crwgdoHnTa7yVw',
    appId: '1:317198605296:android:00830a6266a25cbee35b35',
    messagingSenderId: '317198605296',
    projectId: 'classmate-e1d7f',
    storageBucket: 'classmate-e1d7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWf3dJZd7IYQicNsKJEo2OH4HUdSLAIBI',
    appId: '1:317198605296:ios:b6679d8638370c42e35b35',
    messagingSenderId: '317198605296',
    projectId: 'classmate-e1d7f',
    storageBucket: 'classmate-e1d7f.firebasestorage.app',
    iosBundleId: 'com.example.classmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWf3dJZd7IYQicNsKJEo2OH4HUdSLAIBI',
    appId: '1:317198605296:ios:b6679d8638370c42e35b35',
    messagingSenderId: '317198605296',
    projectId: 'classmate-e1d7f',
    storageBucket: 'classmate-e1d7f.firebasestorage.app',
    iosBundleId: 'com.example.classmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk8VrTqs1uMdwYyWDMkcxwbJvqLotJPVE',
    appId: '1:317198605296:web:5aa7cf2f9604dbc5e35b35',
    messagingSenderId: '317198605296',
    projectId: 'classmate-e1d7f',
    authDomain: 'classmate-e1d7f.firebaseapp.com',
    storageBucket: 'classmate-e1d7f.firebasestorage.app',
    measurementId: 'G-FRGJP2FFL2',
  );
}
